resolver: lts-17.12

packages:
- llvm-hs
- llvm-hs-pure

extra-package-dbs: []

ghc-options:
  llvm-hs: -optcxx=-std=c++11 -optcxx=-lstdc++ -optcxx=-fno-rtti -optcxx=-Wno-init-list-lifetime -optcxx=-Wno-stringop-overflow
